name: Sync Blog to Profile README

on:
  schedule:
    - cron: "0 0 * * *" # 每天运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  update-readme-with-blog:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://www.heyjude.blog/index.xml" # 替换为你的博客 RSS 地址
          max_post_count: 5 # 同步最近 5 篇文章
          readme_path: ./README.md # 目标 README 文件
          commit_message: "Update README with latest blog posts"
